[package]
name = "surtgis-algorithms"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Geospatial algorithms for SurtGis"

[dependencies]
surtgis-core = { path = "../core" }
surtgis-parallel = { path = "../parallel" }
thiserror.workspace = true
anyhow.workspace = true
ndarray.workspace = true
num-traits.workspace = true
ordered-float.workspace = true
rayon.workspace = true
geo.workspace = true
geo-types.workspace = true

[dev-dependencies]
approx.workspace = true
tempfile.workspace = true
criterion.workspace = true

[[bench]]
name = "terrain"
harness = false
